{
    'name': 'Travel & Expense',
    'version': '12.0.1.0.0',
    'summary': 'Travel and Expense Module',
    'description': """Travel and Expense Module""",
    'category': 'Tools',
    'author': 'Indglobal',
    'depends': ['base', 'mail', 'project', 'eci_employee_custom', 'fiscal_year_sequence_extensible', 'hr_employee_kra'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/email_templates.xml',
        'wizard/approver_remark_wizard_view.xml',
        'views/cron.xml',
        'views/travel_claim.xml',
        'views/travel_admin_views.xml',
        'views/hr_travel_master.xml',
        # 'views/hr_travel_views.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
