{
    'name': 'Leave Custom',
    'version': '12.0.1.0.0',
    'summary': 'Validations for leave request',
    'description': """Validations for leave requesthr.leave""",
    'category': 'Tools',
    'author': 'Vishal',
    'depends': ['hr_holidays','hr','hr_leave_calculation', 'base'],
    'data': [
        'security/ir.model.access.csv',
        'security/hr_leave_security.xml',
        'data/leave_cron_data.xml',
        'data/leave_mail_templates.xml',
        'views/hr_leave_type_view.xml',
        'views/hr_leave_view.xml',
        'views/hr_leave_reports.xml',
        'views/hr_leave_allocation_views.xml',
        'views/leave_encash_view.xml',
        'wizard/cancel_leave_wizard_view.xml',
        'data/ir_sequence_data.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
